# Generated by Django 5.0.1 on 2024-02-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_kirim_enterproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kirim',
        ),
    ]
